# Support Vector Machines (SVM)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
ds = pd.read_csv('./data/mushrooms.csv')
ds.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
le = LabelEncoder()
df = ds.apply(le.fit_transform)
df.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [4]:
data = df.values
data = np.array(data)
np.random.shuffle(data)
print(data)

[[0 5 0 ... 3 5 0]
 [0 5 2 ... 2 0 1]
 [1 5 3 ... 7 4 2]
 ...
 [1 5 3 ... 7 4 4]
 [1 5 3 ... 1 4 4]
 [0 2 3 ... 1 4 0]]


In [5]:
x = data[:200,1:]
y = data[:200,0]
y[y==0]=-1
print(x.shape)
print(y.shape)
print(x)
print(y)

(200, 22)
(200,)
[[5 0 4 ... 3 5 0]
 [5 2 8 ... 2 0 1]
 [5 3 4 ... 7 4 2]
 ...
 [2 3 4 ... 7 4 0]
 [2 0 3 ... 3 0 1]
 [2 0 3 ... 1 5 1]]
[-1 -1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1
  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1  1  1 -1 -1  1  1  1 -1  1 -1 -1
  1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1  1 -1  1 -1  1 -1
  1  1 -1  1  1 -1 -1  1  1  1  1 -1  1  1 -1  1 -1  1  1 -1 -1 -1  1 -1
  1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1
  1 -1  1 -1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1  1
  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1  1 -1  1  1 -1 -1  1  1  1 -1  1  1
 -1  1  1 -1  1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1 -1  1
  1 -1 -1  1  1  1 -1  1]


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 22)
(40, 22)
(160,)
(40,)


In [8]:
def hypothesis(w, x, b):
    return np.dot(w,x.T)+b
res = hypothesis(np.random.random((22,)),x_train,0)
print(res.shape)
print(res)
print(y_train)

(160,)
[33.09251048 30.11366611 30.91527604 30.89834083 32.50604507 25.25180326
 23.27179256 29.42881481 23.7343724  22.53623811 23.4494506  26.5183625
 31.08153709 27.78248771 24.32556656 31.7949893  23.52664038 22.81913847
 27.82085799 28.29620623 31.25434448 32.16637409 32.30897827 24.55015169
 28.78061611 27.81682008 26.35895573 30.50930117 33.84042979 23.60046731
 27.84030577 25.75503976 30.10082722 27.53151468 23.37960022 28.69182726
 24.70738124 31.46518509 26.91814665 27.95245277 27.96299745 18.72624782
 22.78329324 31.39486388 32.07615067 22.77615578 17.82392834 28.33747117
 26.01911025 29.75646867 35.92753727 33.55570879 26.25388111 28.00864441
 25.12656802 31.97039674 31.14862174 17.54621703 26.77371082 19.02968362
 32.44807681 24.84133938 18.22037762 35.74840546 26.40723267 22.78175323
 27.05743988 17.07324685 24.17335053 29.65530419 27.02193181 26.70311203
 29.63843325 23.64123545 14.10674372 29.55371188 29.68341706 23.79574293
 26.32374094 28.88681037 29.47927018 33.87533

In [9]:
def hingeLoss(w, x, b, y):
        loss = 0
        # |w|^2 = w * w.T
        loss += 0.5*np.dot(w,w.T)
        ti = np.multiply(y,hypothesis(w,x,b))
        ti = 1-ti
        # Only keeping ti>0
        ti = ti[ti>0]
        loss += np.sum(ti)
        return loss
print(hingeLoss(np.random.random((22,)),x_train,10,y_train))

2759.2349325413024


In [10]:
def fit(x, y, learning_rate=0.001,n_epochs=500):
    n_features = x.shape[1]
    n_samples = x.shape[0]
    w = np.random.random((n_features,))
    b = 0.0
    c = 1.0
    losses = []
    for epoch in range(n_epochs):
        l = hingeLoss(w, x, b, y)
        losses.append(l)
        gradw = np.zeros((n_features,))
        gradb = 0
        ti = np.multiply(y, hypothesis(w, x, b))
        for ix in range(n_features):
            for jx in range(ti.shape[0]):
                if ti[jx]>1:
                    gradw[ix] += 0
                    gradb += 0
                else:
                    gradw[ix] += c*x[jx][ix]*y[jx]
                    gradb += c*y[jx]
        w = w - learning_rate*w + learning_rate*gradw
        b = b + learning_rate*gradb        
    return w,b
wf,bf = fit(x_train,y_train)

In [11]:
def accuracy(x,y):
    hx = hypothesis(wf, x, bf)
    hx[hx>=0]=1
    hx[hx<0]=-1
    print(float(hx[hx==y].shape[0])/y.shape[0])
accuracy(x_test,y_test)

0.85
